### ISSUE TITLE
DTFR User input specification

### ISSUE THREAD

**Issue by AmeliaJo** [njoy/NJOY2016-manual#6]
pg. 391 specifies that Nin should be binary, but later descriptions and Test Case 3 on pg. 731 contradict that.

**Comment by jlconlin** [comment]
That is a good question. On page 392 it says:

> nin must be an output tape from GROUPR, and it can be in either binary or
coded mode.

I suspect the description stating that it must be binary is incorrect.

**Comment by jlconlin** [comment]
Also the code explicitly allows it—and even checks for it. I guess I'll have to update the documentation.
